import type { Language } from "./types";

/**
 * Bundled fallback list — used when /api/languages is unreachable.
 * Keep in sync with apps/server/app/languages.py
 */
export const BUNDLED_LANGUAGES: Language[] = [
  { code: "auto", iso: "auto", name: "Auto-detect", native: "Auto-detect", flag: "🌐" },
  // Major world languages
  { code: "en-US", iso: "en", name: "English", native: "English", flag: "🇺🇸" },
  { code: "en-GB", iso: "en-GB", name: "English (UK)", native: "English (UK)", flag: "🇬🇧" },
  { code: "zh-CN", iso: "zh", name: "Chinese (Simplified)", native: "中文(简体)", flag: "🇨🇳" },
  { code: "zh-TW", iso: "zh-TW", name: "Chinese (Traditional)", native: "中文(繁體)", flag: "🇹🇼" },
  { code: "es-ES", iso: "es", name: "Spanish", native: "Español", flag: "🇪🇸" },
  { code: "es-MX", iso: "es-MX", name: "Spanish (Mexico)", native: "Español (México)", flag: "🇲🇽" },
  { code: "fr-FR", iso: "fr", name: "French", native: "Français", flag: "🇫🇷" },
  { code: "de-DE", iso: "de", name: "German", native: "Deutsch", flag: "🇩🇪" },
  { code: "ru-RU", iso: "ru", name: "Russian", native: "Русский", flag: "🇷🇺" },
  { code: "pt-BR", iso: "pt", name: "Portuguese (Brazil)", native: "Português (Brasil)", flag: "🇧🇷" },
  { code: "pt-PT", iso: "pt-PT", name: "Portuguese (Portugal)", native: "Português (Portugal)", flag: "🇵🇹" },
  { code: "ja-JP", iso: "ja", name: "Japanese", native: "日本語", flag: "🇯🇵" },
  { code: "ko-KR", iso: "ko", name: "Korean", native: "한국어", flag: "🇰🇷" },
  { code: "ar-SA", iso: "ar", name: "Arabic", native: "العربية", flag: "🇸🇦" },
  { code: "hi-IN", iso: "hi", name: "Hindi", native: "हिन्दी", flag: "🇮🇳" },
  { code: "it-IT", iso: "it", name: "Italian", native: "Italiano", flag: "🇮🇹" },
  { code: "tr-TR", iso: "tr", name: "Turkish", native: "Türkçe", flag: "🇹🇷" },
  { code: "nl-NL", iso: "nl", name: "Dutch", native: "Nederlands", flag: "🇳🇱" },
  { code: "pl-PL", iso: "pl", name: "Polish", native: "Polski", flag: "🇵🇱" },
  { code: "uk-UA", iso: "uk", name: "Ukrainian", native: "Українська", flag: "🇺🇦" },
  { code: "sv-SE", iso: "sv", name: "Swedish", native: "Svenska", flag: "🇸🇪" },
  { code: "da-DK", iso: "da", name: "Danish", native: "Dansk", flag: "🇩🇰" },
  { code: "no-NO", iso: "no", name: "Norwegian", native: "Norsk", flag: "🇳🇴" },
  { code: "fi-FI", iso: "fi", name: "Finnish", native: "Suomi", flag: "🇫🇮" },
  { code: "ro-RO", iso: "ro", name: "Romanian", native: "Română", flag: "🇷🇴" },
  { code: "hu-HU", iso: "hu", name: "Hungarian", native: "Magyar", flag: "🇭🇺" },
  { code: "cs-CZ", iso: "cs", name: "Czech", native: "Čeština", flag: "🇨🇿" },
  { code: "sk-SK", iso: "sk", name: "Slovak", native: "Slovenčina", flag: "🇸🇰" },
  { code: "bg-BG", iso: "bg", name: "Bulgarian", native: "Български", flag: "🇧🇬" },
  { code: "hr-HR", iso: "hr", name: "Croatian", native: "Hrvatski", flag: "🇭🇷" },
  { code: "sr-RS", iso: "sr", name: "Serbian", native: "Српски", flag: "🇷🇸" },
  { code: "el-GR", iso: "el", name: "Greek", native: "Ελληνικά", flag: "🇬🇷" },
  { code: "he-IL", iso: "he", name: "Hebrew", native: "עברית", flag: "🇮🇱" },
  { code: "th-TH", iso: "th", name: "Thai", native: "ไทย", flag: "🇹🇭" },
  { code: "vi-VN", iso: "vi", name: "Vietnamese", native: "Tiếng Việt", flag: "🇻🇳" },
  { code: "id-ID", iso: "id", name: "Indonesian", native: "Bahasa Indonesia", flag: "🇮🇩" },
  { code: "ms-MY", iso: "ms", name: "Malay", native: "Bahasa Melayu", flag: "🇲🇾" },
  { code: "tl-PH", iso: "tl", name: "Filipino", native: "Filipino", flag: "🇵🇭" },
  { code: "bn-BD", iso: "bn", name: "Bengali", native: "বাংলা", flag: "🇧🇩" },
  { code: "ta-IN", iso: "ta", name: "Tamil", native: "தமிழ்", flag: "🇮🇳" },
  { code: "ur-PK", iso: "ur", name: "Urdu", native: "اردو", flag: "🇵🇰" },
  { code: "fa-IR", iso: "fa", name: "Persian", native: "فارسی", flag: "🇮🇷" },
  { code: "sw-KE", iso: "sw", name: "Swahili", native: "Kiswahili", flag: "🇰🇪" },
  { code: "af-ZA", iso: "af", name: "Afrikaans", native: "Afrikaans", flag: "🇿🇦" },
  { code: "ka-GE", iso: "ka", name: "Georgian", native: "ქართული", flag: "🇬🇪" },
  { code: "az-AZ", iso: "az", name: "Azerbaijani", native: "Azərbaycan", flag: "🇦🇿" },
  { code: "kk-KZ", iso: "kk", name: "Kazakh", native: "Қазақша", flag: "🇰🇿" },
  { code: "uz-UZ", iso: "uz", name: "Uzbek", native: "O'zbek", flag: "🇺🇿" },
];
